### ISSUE TITLE
amplitude isn't loudness

### ISSUE THREAD

**Issue by jefftrevino** [joshwcomeau/waveforms#3]
The text is lucidly written, but it claims at multiple points that physical displacement is the same as loudness. It's a subtle point, but an important one, I think, that amplitude is a physical measure of displacement, while loudness is a perceptual corollate of amplitude. The definition of loudness is "how loud a sound sounds," while the definition of a wave's amplitude is something like "the magnitude of physical displacement of a medium's particles due to a wave's propagation through the medium." (That is, amplitude is a measure of the effect of the wave's propagation.) This becomes important when we throw timbre into the mix: if I hear a scream from a large distance away, I will probably still call this a "loud" sound -- due to its timbre, and my intuition that it would sound loud at a short distance -- even though the amplitude at my point of audition would not be very high.

**Comment by joshwcomeau** [comment]
Yeah, that's a fair point. I can rephrase the original definition, although I'm wary of getting too "in the weeds". The goal is really to give the reader (without an audio background) a sense of how sound works, and so comprehension is more important than accuracy (although, obviously, I tried not to say anything blatantly false, just oversimplified).

I'll play with the wording and see if I can get anything satisfactory. Thanks for the feedback!

**Comment by joshwcomeau** [comment]
[Updated the copy](https://github.com/joshwcomeau/waveforms/commit/bc57bf89916bb074c000388a296c44de1311fd71) to clarify the loudness points.

Closing the issue as I believe I've addressed the concern, but feel free to reopen if there's more worthwhile discussion to be had!
