### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by samueloph** [joshwcomeau/waveforms#6]
Hello, i just finished reading this and i loved it, it would be awesome if i could share this with people who doesn't speak english.
Would you be interested in receiving translations?
I mean, i don't know how much trouble would be to add a language selector (is it better to fork it and translate instead?)

**Comment by joshwcomeau** [comment]
Thanks for the kind words!

So, yeah, I'd love to support i18n. It's non-trivial to support, though, and I'm a bit over-extended right now (juggling too many side-projects in addition to my full-time job).

I'd recommend forking it and changing it. Most of the text lives in `IntroRoute.steps.js`, with some in `IntroRouteEnd.js`, as well as some stuff scattered around. 

If you do fork and translate it, please let me know! I do plan to circle back to this at some point, and having it translated already in another language would be awesome and helpful.

**Comment by samueloph** [comment]
Thanks @joshwcomeau, a translation is already on the way, i'll ping you once it's completed and online.
